/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-yaml-dts. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

export {}

declare module "vue-i18n" {
  export interface DefineLocaleMessage {
    "instrata": string
    "common": {
      "not-implemented": string
    }
    "home": {
      "search-for-guides": string
      "clear-search": string
      "import-guide": string
      "new-guide": string
      "your-guides": string
      "display-as-list": string
      "display-as-grid": string
      "import-dropzone": {
        "title": string
        "description": string
      }
      "card-actions": {
        "view": string
        "duplicate": string
        "export": string
        "delete": string
      }
    }
    "app": {
      "controls": {
        "home": string
        "take-screenshot": string
      }
      "export-dialog": {
        "label": string
        "common": {
          "export": string
        }
        "pdf": {
          "label": string
          "title": string
          "description": string
          "fields": {
            "template": {
              "label": string
              "description": string
            }
          }
        }
        "markdown": {
          "label": string
          "title": string
          "description": string
          "fields": {
            "template": {
              "label": string
              "description": string
            }
          }
        }
      }
      "placeholder": {
        "title": string
        "abstract": string
        "footnote": string
      }
      "node-menu": {
        "move-up": string
        "move-down": string
        "delete": string
      }
      "text-editor": {
        "toggle-bold": string
        "toggle-italic": string
        "toggle-hyperref": string
        "toggle-code": string
        "toggle-code-block": string
        "toggle-blockquote": string
        "toggle-unordered-list": string
        "toggle-ordered-list": string
        "undo": string
        "redo": string
        "clear-formatting": string
        "toggle-formatting-marks": string
      }
    }
    "settings": {
      "label": string
      "general": {
        "label": string
        "appearance": {
          "heading": string
          "theme": {
            "label": string
            "system": string
            "light": string
            "dark": string
          }
        }
        "additional-settings": {
          "heading": string
          "developer-mode": string
        }
      }
      "languages": {
        "label": string
        "locale": string
      }
      "keybindings": {
        "label": string
      }
      "templates": {
        "label": string
        "open-directory-tooltip": string
        "card": {
          "by": string
        }
      }
      "about": {
        "label": string
        "version": string
        "organization": string
        "repository": string
        "report-bug": string
        "suggest-feature": string
        "copyright": string
      }
      "developers": {
        "label": string
        "locations": {
          "heading": string
          "app-config": string
          "app-data": string
        }
        "runtime-info": {
          "heading": string
          "os": string
          "install": string
          "arch": string
        }
        "update": {
          "heading": string
        }
      }
    }
  }
}
