/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-yaml-dts. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

export {}

declare module "vue-i18n" {
  export interface DefineLocaleMessage {
    settings: {
      languages: {
        label: string
        locale: string
      }
    }
  }
}
