name: Build & Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install frontend dependencies
        run: npm clean-install

      - name: TypeScript check
        run: npm run type-check

      - name: i18n check
        run: npm run i18n-check

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          # tauri
          sudo apt-get install -y \
              libwebkit2gtk-4.1-dev build-essential libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev \
          # xcap
          sudo apt-get install -y \
              pkg-config libclang-dev libxcb1-dev libxrandr-dev libdbus-1-dev libpipewire-0.3-dev libwayland-dev libegl-dev libgbm-dev

      - name: Rust check
        working-directory: src-tauri
        run: cargo check --locked

  build:
    needs: preflight
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Frontend Dependencies
        run: npm clean-install

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # tauri
          sudo apt-get install -y \
              libwebkit2gtk-4.1-dev build-essential libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev \
          # xcap
          sudo apt-get install -y \
              pkg-config libclang-dev libxcb1-dev libxrandr-dev libdbus-1-dev libpipewire-0.3-dev libwayland-dev libegl-dev libgbm-dev

      - name: Build (Tauri)
        run: npm run tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""

      - name: Collect Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          set -e; shopt -s nullglob
          mkdir -p release-artifacts
          
          mv src-tauri/target/release/bundle/msi/*.msi release-artifacts/instrata-x86_64.msi
          mv src-tauri/target/release/bundle/msi/*.msi.sig release-artifacts/instrata-x86_64.msi.sig
          
          mv src-tauri/target/release/bundle/nsis/*-setup.exe release-artifacts/instrata-x86_64-setup.exe
          mv src-tauri/target/release/bundle/nsis/*-setup.exe.sig release-artifacts/instrata-x86_64-setup.exe.sig

      - name: Collect Artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          set -e; shopt -s nullglob
          mkdir -p release-artifacts
          
          mv src-tauri/target/release/bundle/appimage/*.AppImage release-artifacts/instrata-x86_64.AppImage
          mv src-tauri/target/release/bundle/appimage/*.AppImage.sig release-artifacts/instrata-x86_64.AppImage.sig
          
          mv src-tauri/target/release/bundle/deb/*.deb release-artifacts/instrata-x86_64.deb
          mv src-tauri/target/release/bundle/deb/*.deb.sig release-artifacts/instrata-x86_64.deb.sig
          
          mv src-tauri/target/release/bundle/rpm/*.rpm release-artifacts/instrata-x86_64.rpm
          mv src-tauri/target/release/bundle/rpm/*.rpm.sig release-artifacts/instrata-x86_64.rpm.sig

      - name: Collect Artifacts (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          set -e; shopt -s nullglob
          mkdir -p release-artifacts
          
          mv src-tauri/target/release/bundle/dmg/*.dmg release-artifacts/instrata-arm64.dmg
          mv src-tauri/target/release/bundle/dmg/*.dmg.sig release-artifacts/instrata-arm64.dmg.sig
          
          mv src-tauri/target/release/bundle/macos/*.app.tar.gz release-artifacts/instrata-arm64.app.tar.gz
          mv src-tauri/target/release/bundle/macos/*.app.tar.gz.sig release-artifacts/instrata-arm64.app.tar.gz.sig

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: instrata-${{ matrix.os }}
          path: |
            release-artifacts/*
          if-no-files-found: error

      - name: Bundle Cleanup
        run: |
          node -e "const fs=require('fs');fs.rmSync('src-tauri/target/release/bundle',{recursive:true,force:true});"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Generate updater.json
        run: node scripts/generate-updater.cjs
        env:
          VERSION: ${{ github.ref_name }}
          REPO: ${{ github.repository }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.ref_name }}
          name: "Instrata ${{ github.ref_name }}"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            release-artifacts/instrata-windows-latest/instrata-x86_64.msi
            release-artifacts/instrata-windows-latest/instrata-x86_64-setup.exe
            release-artifacts/instrata-ubuntu-latest/instrata-x86_64.AppImage
            release-artifacts/instrata-ubuntu-latest/instrata-x86_64.deb
            release-artifacts/instrata-ubuntu-latest/instrata-x86_64.rpm
            release-artifacts/instrata-macos-latest/instrata-arm64.dmg
            release-artifacts/instrata-macos-latest/instrata-arm64.app.tar.gz
            release-artifacts/updater.json
